<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DigitalDoor.Reporting" Version="1.17.71" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.8" />
	</ItemGroup>

</Project>
